/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Admin
 */
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.*;
public class Bill_for_Cust_s extends javax.swing.JFrame {

    /**
     * Creates new form Bill_for_Cust_s
     */
    public Bill_for_Cust_s() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tf6 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tf4 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tf5 = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        tf2 = new javax.swing.JTextField();
        tf3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tf8 = new javax.swing.JTextField();
        tf9 = new javax.swing.JTextField();
        tf7 = new javax.swing.JTextField();
        tf10 = new javax.swing.JTextField();
        tf1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        jLabel1.setText("AAdhar Number");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(29, 63, 162, 23);

        jLabel4.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        jLabel4.setText("Address");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 230, 120, 23);

        jLabel2.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        jLabel2.setText("Phone Number");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(599, 65, 150, 23);

        tf6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        getContentPane().add(tf6);
        tf6.setBounds(579, 362, 140, 40);

        jLabel12.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        jLabel12.setText("Price");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(490, 360, 80, 40);

        jLabel3.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        jLabel3.setText("Name");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 130, 83, 40);

        tf4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        getContentPane().add(tf4);
        tf4.setBounds(220, 120, 820, 60);

        tf5.setColumns(20);
        tf5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        tf5.setRows(5);
        jScrollPane2.setViewportView(tf5);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(220, 190, 531, 120);

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel7.setText("Seller");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(942, 13, 90, 30);

        tf2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        tf2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf2ActionPerformed(evt);
            }
        });
        tf2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf2KeyTyped(evt);
            }
        });
        getContentPane().add(tf2);
        tf2.setBounds(220, 50, 274, 60);

        tf3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        tf3.setToolTipText("Enter Only Number");
        tf3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf3ActionPerformed(evt);
            }
        });
        getContentPane().add(tf3);
        tf3.setBounds(780, 50, 256, 60);

        jLabel6.setText("Bill No.");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(12, 13, 69, 30);

        jButton1.setFont(new java.awt.Font("Verdana", 3, 24)); // NOI18N
        jButton1.setText("Save & Print");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(780, 200, 250, 240);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Vehicle", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Verdana", 3, 24))); // NOI18N
        jPanel1.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        jLabel8.setText("Company");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(10, 50, 100, 40);

        jLabel9.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        jLabel9.setText("Model");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(10, 110, 90, 30);

        jLabel10.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        jLabel10.setText("Vehicle No.");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(10, 160, 130, 30);

        jLabel11.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        jLabel11.setText("Smart Card");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(10, 210, 130, 40);

        tf8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel1.add(tf8);
        tf8.setBounds(169, 50, 230, 40);

        tf9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel1.add(tf9);
        tf9.setBounds(169, 100, 230, 40);

        tf7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel1.add(tf7);
        tf7.setBounds(169, 160, 230, 40);

        tf10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel1.add(tf10);
        tf10.setBounds(169, 220, 230, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 310, 430, 290);
        getContentPane().add(tf1);
        tf1.setBounds(86, 17, 76, 22);

        jButton2.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        jButton2.setText("Create Another Bill");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(460, 470, 250, 110);

        jButton3.setFont(new java.awt.Font("Verdana", 3, 24)); // NOI18N
        jButton3.setText("Back To Main");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(770, 470, 250, 110);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf2ActionPerformed

    private void tf2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf2KeyTyped

    }//GEN-LAST:event_tf2KeyTyped

    private void tf3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf3ActionPerformed

    }//GEN-LAST:event_tf3ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Main m=new Main();
        m.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        tf2.setText("");
        tf3.setText("");
        tf4.setText("");
        tf1.setText("");
        tf6.setText("");
        tf8.setText("");
        tf9.setText("");
        tf7.setText("");
        tf10.setText("");
        tf5.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String a=tf1.getText();
        String b=tf2.getText();
        String c=tf3.getText();
        String d=tf4.getText();
        String e1=tf5.getText();
        String f=tf7.getText();
        String g=tf6.getText();
        String h=tf8.getText();
        String i=tf9.getText();
        String j=tf10.getText();
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mysql","root","");
            String query = "insert into billsell values('"+a+"','"+b+"','"+c+"','"+d+"','"+e1+"','"+f+"','"+g+"');";
            Statement s=(Statement) con.createStatement();
            int success;
            success = s.executeUpdate(query);
            if(success==1)
            {
                JOptionPane.showMessageDialog(this,"Successful");
            }
            else
            {
                JOptionPane.showMessageDialog(this,"Problem in Saving, Retry");
            }
        }
        catch(ClassNotFoundException | SQLException | HeadlessException e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mysql","root","");
            String query = "insert into vehicle values('"+h+"','"+i+"','"+g+"','"+j+"');";
            Statement s=(Statement) con.createStatement();
            int success;
            success = s.executeUpdate(query);
            if(success==1)
            {
                JOptionPane.showMessageDialog(this,"Successful");
            }
            else
            {
                JOptionPane.showMessageDialog(this,"Problem in Saving, Retry");
            }
        }
        catch(ClassNotFoundException | SQLException | HeadlessException e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bill_for_Cust_s.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bill_for_Cust_s.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bill_for_Cust_s.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bill_for_Cust_s.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bill_for_Cust_s().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField tf1;
    private javax.swing.JTextField tf10;
    private javax.swing.JTextField tf2;
    private javax.swing.JTextField tf3;
    private javax.swing.JTextField tf4;
    private javax.swing.JTextArea tf5;
    private javax.swing.JTextField tf6;
    private javax.swing.JTextField tf7;
    private javax.swing.JTextField tf8;
    private javax.swing.JTextField tf9;
    // End of variables declaration//GEN-END:variables
}
